seed: 1
num_worker: 2
work_dir: ./work_dir/synth/

phase: train

feeder: feeders.feeder_ntu.Feeder

train_feeder_args:
  data_path: /home/fzhi/fzt/skateformer/SkateFormer/data/playroom/Thuman00/joint_3d_keypoint/npy/skateformer_data/SYNTH_CS.npz  # 你把 SYNTH_CS.npz 放到 data/ntu/ 下
  split: train
  debug: False
  window_size: 64
  p_interval: [0.5, 1]
  aug_method: a123489
  intra_p: 0.5
  inter_p: 0.2
  thres: 64
  uniform: True
  partition: True

test_feeder_args:
  data_path: /home/fzhi/fzt/skateformer/SkateFormer/data/playroom/Thuman00/joint_3d_keypoint/npy/skateformer_data/SYNTH_CS.npz
  split: test
  window_size: 64
  p_interval: [0.95]
  thres: 64
  uniform: True
  partition: True
  debug: False

model: model.SkateFormer.SkateFormer_
model_args:
  num_classes: 1       # 你现在只有 1 个类别
  num_people: 2
  num_points: 24       # 保持和原 NTU config 一致，Feeder 里会处理
  kernel_size: 7
  num_heads: 32
  attn_drop: 0.5
  head_drop: 0.0
  rel: True
  drop_path: 0.2
  type_1_size: [8, 8]
  type_2_size: [8, 12]
  type_3_size: [8, 8]
  type_4_size: [8, 12]
  mlp_ratio: 4.0
  index_t: True

optimizer: AdamW
weight_decay: 0.1
lr_scheduler: cosine
base_lr: 1e-4
min_lr: 1e-5
warmup_lr: 1e-7
warmup_prefix: False
warm_up_epoch: 5

device: [0]
batch_size: 1
test_batch_size: 1
num_epoch: 50
nesterov: True
grad_clip: True
grad_max: 1.0
loss_type: CE
